import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { resolve } from 'node:path';

const root=resolve(import.meta.dirname,'..');
const html=await readFile(resolve(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'https://tech-review.local/',runScripts:'outside-only'});
dom.window.scrollTo=()=>{};
dom.window.HTMLElement.prototype.scrollIntoView=()=>{};
for(const file of ['questions.js','question-expander.js','ax-question-extension.js','learning-os-data.js','atlas-content.js','app.js','learning-os.js']) dom.window.eval(await readFile(resolve(root,file),'utf8'));
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
assert(dom.window.QUESTION_BANK.length===5000,'question count must be 5000');
assert(dom.window.document.getElementById('totalStat').textContent==='5000','home total must display 5000');
assert(dom.window.searchKnowledge('RAG').length>0,'RAG search must return results');
assert(dom.window.getRelatedQuestions('MCP').length>0,'related questions must work');
assert(dom.window.getWhyExplanation(dom.window.QUESTION_BANK[0].id),'Why explanation must exist');
assert(Object.keys(dom.window.ATLAS_CHAPTERS).length===7,'seven deep-dive chapters must exist');
assert(dom.window.ATLAS_CHAPTERS['AI & Design'].interviews.length===20,'each chapter needs TOP20 interviews');
assert(dom.window.QUESTION_BANK.every(q=>q.metadata.company&&q.prerequisites&&q.nextTopics),'enhanced metadata must exist');
dom.window.document.getElementById('startBtn').click();
const option=dom.window.document.querySelector('.option');assert(option,'quiz option must render');option.click();
assert(!dom.window.document.getElementById('answerPanel').hidden,'answer panel must open');
dom.window.document.getElementById('whyBtn').click();
assert(!dom.window.document.getElementById('whyPanel').hidden,'Why panel must open');
dom.window.document.getElementById('homeSearchInput').value='Prompt Injection';
dom.window.document.getElementById('homeSearchForm').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
assert(dom.window.document.getElementById('knowledgeView').classList.contains('active'),'search view must open');
assert(dom.window.document.querySelectorAll('.result-item').length>0,'search results must render');
console.log('Smoke test passed: 5000 questions, quiz, Why, search, related topics.');
