import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { resolve } from 'node:path';

const root=resolve(import.meta.dirname,'..');
const html=await readFile(resolve(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'https://tech-review.local/learn/?job=qa-job-42&topic=LocalStorage',runScripts:'outside-only'});
dom.window.scrollTo=()=>{};
dom.window.HTMLElement.prototype.scrollIntoView=()=>{};
for(const file of ['questions.js','question-expander.js','ax-question-extension.js','learning-os-data.js','atlas-content.js','curriculum-data.js','developer-guide-data.js','learning-visuals.js','app.js','learning-os.js']) dom.window.eval(await readFile(resolve(root,file),'utf8'));
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const versionedAssets=[...dom.window.document.querySelectorAll('script[src],link[href],img[src]')]
  .map(node=>node.getAttribute('src')||node.getAttribute('href'))
  .filter(value=>value&&!value.startsWith('#'));
assert(versionedAssets.every(value=>value.includes('?v=backend-atlas-v10-verified-contract')),'every release asset reference must use the verified-contract cache key');
const serviceWorker=await readFile(resolve(root,'sw.js'),'utf8');
assert(!serviceWorker.includes('caches.match'),'service worker must not hide stable-filename release assets');
assert(dom.window.QUESTION_BANK_QUALITY_CONTRACT?.mode==='reviewed-only','public question bank must use the reviewed-only contract');
assert(dom.window.QUESTION_BANK.length===dom.window.QUESTION_BANK_QUALITY_CONTRACT.publicQuestionCount,'public question count must match the quality contract');
assert(dom.window.document.getElementById('totalStat').textContent===String(dom.window.QUESTION_BANK.length),'home total must display the reviewed public count');
assert(dom.window.document.getElementById('bulkBtn').textContent.includes(`${dom.window.QUESTION_BANK.length}문제`),'full reviewed-set CTA must show the actual available question count');
assert(dom.window.document.getElementById('reviewedSetNote').textContent.includes('개념 187개 중 4개'),'home must disclose the reviewed concept scope before learners enter the curriculum');
assert(dom.window.searchKnowledge('RAG').length>0,'RAG search must return results');
assert(dom.window.getRelatedQuestions('B-Tree').length>0,'related reviewed questions must work');
assert(dom.window.getWhyExplanation(dom.window.QUESTION_BANK[0].id),'Why explanation must exist');
assert(Object.keys(dom.window.ATLAS_CHAPTERS).length===7,'seven deep-dive chapters must exist');
assert(dom.window.ATLAS_CHAPTERS['AI & Design'].interviews.length===20,'each chapter needs TOP20 interviews');
assert(dom.window.QUESTION_BANK.every(q=>q.metadata?.source==='direct-source-reviewed'&&q.metadata?.reviewerId==='atlas-source-review'&&Array.isArray(q.prerequisites)&&Array.isArray(q.nextTopics)),'direct-source-reviewed learning metadata must exist');
assert(dom.window.QUESTION_BANK.every(q=>q.type&&q.optionReasons?.length===4),'question type and option reasons required');
assert(dom.window.findCurriculumConcept('ArrayList'),'Java fundamentals must be searchable');
assert(dom.window.findCurriculumConcept('LocalStorage')?.title==='Web Storage API','LocalStorage alias must resolve to Web Storage API');
assert(dom.window.findCurriculumConcept('RAG latency')?.title==='RAG','token-boundary prefix search must resolve RAG phrases');
assert(!String(dom.window.findCurriculumConcept('LocalStorage')?.definition).includes('RAG'),'LocalStorage must not false-match the RAG substring');
assert(dom.window.document.getElementById('knowledgeView').classList.contains('active'),'Incruit handoff must open the knowledge view');
assert(dom.window.document.getElementById('knowledgeSearchInput').value==='LocalStorage','Incruit topic must populate the search input');
assert(dom.window.document.querySelector('[data-testid="incruit-handoff-context"]'),'Incruit handoff context must be visible');
assert(dom.window.document.querySelector('.encyclopedia-card h2').textContent==='Web Storage API','handoff must resolve the requested alias to its reviewed curriculum concept');
assert(dom.window.document.querySelector('.encyclopedia-definition').textContent.includes('브라우저 origin별'),'LocalStorage handoff must show Web Storage content');
dom.window.document.getElementById('navHomeBtn').click();
assert(dom.window.ATLAS_CURRICULUM['Java & Spring'].sections.length>=6,'Java curriculum must cover core, concurrency, JVM and Spring');
assert(dom.window.QUESTION_BANK.filter(q=>q.category==='Java & Spring'&&q.reviewStatus==='reviewed').length>=7,'Java fundamentals need dedicated reviewed questions');
assert(Object.values(dom.window.ATLAS_CURRICULUM).flatMap(c=>c.sections).flatMap(s=>s.concepts).every(c=>c.comparison),'every curriculum concept needs a comparison table');
dom.window.document.getElementById('navStudyBtn').click();
assert(dom.window.document.querySelectorAll('.curriculum-card').length===7,'study home must render seven category cards');
Array.from(dom.window.document.querySelectorAll('[data-curriculum]')).find(node=>node.dataset.curriculum==='Java & Spring').click();
assert(dom.window.document.querySelectorAll('.section-card').length>=6,'Java study must render focused chapter cards');
  const servletConcept=[...dom.window.document.querySelectorAll('[data-concept]')].find(node=>node.textContent.includes('Servlet과 Container'));
  assert(servletConcept,'Servlet curriculum concept must be available');
  servletConcept.click();
assert(dom.window.document.querySelectorAll('.concept-tab').length===5,'concept detail must provide five focused tabs');
assert(dom.window.document.querySelector('.summary-card'),'concept detail must start with summary card');
dom.window.document.querySelector('[data-tab="principle"]').click();
assert(dom.window.document.querySelector('.learning-visual svg[role="img"][aria-label*="Servlet"]'),'principle tab must render the curated accessible Servlet lifecycle diagram');
assert(dom.window.history.state.route==='concept','concept navigation must be stored in browser history');
dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate',{state:{route:'study-category',category:'Java & Spring'}}));
assert(dom.window.document.querySelectorAll('.section-card').length>=6,'history restoration must return to previous study category');
dom.window.document.getElementById('navArchitectureBtn').click();
assert(dom.window.document.querySelectorAll('.project-guide-card').length===3,'developer guide must list three projects');
Array.from(dom.window.document.querySelectorAll('[data-project]')).find(node=>node.dataset.project==='Archive Nexus').click();
assert(dom.window.document.querySelectorAll('.guide-section').length>=8,'project guide must cover architecture concerns');
assert(dom.window.document.querySelectorAll('.guide-node').length>=10,'project guide must render responsive interactive flow nodes');
dom.window.document.querySelector('.guide-node').click();assert(!dom.window.document.querySelector('.node-detail').hidden,'guide node must expose role, input and output');
dom.window.localStorage.removeItem('backendAtlasQuizSession');
dom.window.document.getElementById('startBtn').click();
const option=dom.window.document.querySelector('.option');assert(option,'quiz option must render');option.click();
const persisted=JSON.parse(dom.window.localStorage.getItem('backendAtlasQuizSession'));assert(persisted?.selectedAnswers&&persisted.questionIds.length===Math.min(10,dom.window.QUESTION_BANK.length),`quiz answer and reviewed order must persist immediately (actual ${persisted?.questionIds?.length||0})`);
assert(!dom.window.document.getElementById('answerPanel').hidden,'answer panel must open');
assert(dom.window.document.querySelectorAll('.option-reason').length===4,'answer must explain every option');
dom.window.document.getElementById('whyBtn').click();
assert(!dom.window.document.getElementById('whyPanel').hidden,'Why panel must open');
dom.window.document.getElementById('homeSearchInput').value='B-Tree';
dom.window.document.getElementById('homeSearchForm').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
assert(dom.window.document.getElementById('knowledgeView').classList.contains('active'),'search view must open');
assert(dom.window.document.querySelector('.encyclopedia-card h2')?.textContent==='B-Tree','search must put the exact reviewed encyclopedia entry first');
assert(dom.window.document.querySelectorAll('.supplement-result').length>=2,'B-Tree search must render its reviewed principle and write-cost questions');
dom.window.document.getElementById('knowledgeSearchInput').value='ArrayList';
dom.window.document.getElementById('knowledgeSearchForm').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
assert(dom.window.document.querySelector('.encyclopedia-card h2').textContent.includes('ArrayList'),'concept search must render the matching encyclopedia title');
assert(dom.window.document.querySelector('.comparison-table'),'concept comparison table must render');
dom.window.document.getElementById('knowledgeSearchInput').value='미등록검사용어';
dom.window.document.getElementById('knowledgeSearchForm').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
assert(!dom.window.document.querySelector('.encyclopedia-card'),'unknown terms must not fabricate an encyclopedia entry');
assert(dom.window.document.querySelector('.no-verified-entry h2')?.textContent==='등록된 개념이 없습니다','unknown terms must show an explicit no-verified-content state');
assert(!dom.window.document.querySelector('.supplement-result'),'unknown terms must not attach unrelated learning results');
console.log(`Smoke test passed: ${dom.window.QUESTION_BANK.length} reviewed questions, quiz, Why, search, related topics.`);
