import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { resolve } from 'node:path';

const root=resolve(import.meta.dirname,'..');
const html=await readFile(resolve(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'https://tech-review.local/',runScripts:'outside-only'});
dom.window.scrollTo=()=>{};
dom.window.HTMLElement.prototype.scrollIntoView=()=>{};
for(const file of ['questions.js','question-expander.js','ax-question-extension.js','learning-os-data.js','atlas-content.js','curriculum-data.js','developer-guide-data.js','learning-visuals.js','app.js','learning-os.js']) dom.window.eval(await readFile(resolve(root,file),'utf8'));
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
assert(dom.window.QUESTION_BANK.length===5000,'question count must be 5000');
assert(dom.window.document.getElementById('totalStat').textContent==='5000','home total must display 5000');
assert(dom.window.searchKnowledge('RAG').length>0,'RAG search must return results');
assert(dom.window.getRelatedQuestions('MCP').length>0,'related questions must work');
assert(dom.window.getWhyExplanation(dom.window.QUESTION_BANK[0].id),'Why explanation must exist');
assert(Object.keys(dom.window.ATLAS_CHAPTERS).length===7,'seven deep-dive chapters must exist');
assert(dom.window.ATLAS_CHAPTERS['AI & Design'].interviews.length===20,'each chapter needs TOP20 interviews');
assert(dom.window.QUESTION_BANK.every(q=>q.metadata.company&&q.prerequisites&&q.nextTopics),'enhanced metadata must exist');
assert(dom.window.QUESTION_BANK.every(q=>q.type&&q.optionReasons?.length===4),'question type and option reasons required');
assert(dom.window.findCurriculumConcept('ArrayList'),'Java fundamentals must be searchable');
assert(dom.window.ATLAS_CURRICULUM['Java & Spring'].sections.length>=6,'Java curriculum must cover core, concurrency, JVM and Spring');
assert(dom.window.QUESTION_BANK.filter(q=>q.category==='Java & Spring'&&String(q.id).startsWith('curriculum-')).length>=20,'Java fundamentals need dedicated quality questions');
assert(Object.values(dom.window.ATLAS_CURRICULUM).flatMap(c=>c.sections).flatMap(s=>s.concepts).every(c=>c.comparison),'every curriculum concept needs a comparison table');
dom.window.document.getElementById('navStudyBtn').click();
assert(dom.window.document.querySelectorAll('.curriculum-card').length===7,'study home must render seven category cards');
Array.from(dom.window.document.querySelectorAll('[data-curriculum]')).find(node=>node.dataset.curriculum==='Java & Spring').click();
assert(dom.window.document.querySelectorAll('.section-card').length>=6,'Java study must render focused chapter cards');
dom.window.document.querySelector('[data-concept="0:0"]').click();
assert(dom.window.document.querySelectorAll('.concept-tab').length===5,'concept detail must provide five focused tabs');
assert(dom.window.document.querySelector('.summary-card'),'concept detail must start with summary card');
dom.window.document.querySelector('[data-tab="principle"]').click();
assert(dom.window.document.querySelector('.learning-visual svg'),'principle tab must render a learning diagram');
assert(dom.window.history.state.route==='concept','concept navigation must be stored in browser history');
dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate',{state:{route:'study-category',category:'Java & Spring'}}));
assert(dom.window.document.querySelectorAll('.section-card').length>=6,'history restoration must return to previous study category');
dom.window.document.getElementById('navArchitectureBtn').click();
assert(dom.window.document.querySelectorAll('.project-guide-card').length===3,'developer guide must list three projects');
Array.from(dom.window.document.querySelectorAll('[data-project]')).find(node=>node.dataset.project==='Archive Nexus').click();
assert(dom.window.document.querySelectorAll('.guide-section').length>=8,'project guide must cover architecture concerns');
assert(dom.window.document.querySelectorAll('.guide-node').length>=10,'project guide must render responsive interactive flow nodes');
dom.window.document.querySelector('.guide-node').click();assert(!dom.window.document.querySelector('.node-detail').hidden,'guide node must expose role, input and output');
dom.window.localStorage.removeItem('backendAtlasQuizSession');
dom.window.document.getElementById('startBtn').click();
const option=dom.window.document.querySelector('.option');assert(option,'quiz option must render');option.click();
const persisted=JSON.parse(dom.window.localStorage.getItem('backendAtlasQuizSession'));assert(persisted?.selectedAnswers&&persisted.questionIds.length===10,'quiz answer and order must persist immediately');
assert(!dom.window.document.getElementById('answerPanel').hidden,'answer panel must open');
assert(dom.window.document.querySelectorAll('.option-reason').length===4,'answer must explain every option');
dom.window.document.getElementById('whyBtn').click();
assert(!dom.window.document.getElementById('whyPanel').hidden,'Why panel must open');
dom.window.document.getElementById('homeSearchInput').value='Prompt Injection';
dom.window.document.getElementById('homeSearchForm').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
assert(dom.window.document.getElementById('knowledgeView').classList.contains('active'),'search view must open');
assert(dom.window.document.querySelectorAll('.result-item').length>0,'search results must render');
dom.window.document.getElementById('knowledgeSearchInput').value='ArrayList';
dom.window.document.getElementById('knowledgeSearchForm').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
assert(dom.window.document.querySelector('.concept-search-summary'),'concept search summary must render');
assert(dom.window.document.querySelector('.comparison-table'),'concept comparison table must render');
console.log('Smoke test passed: 5000 questions, quiz, Why, search, related topics.');
